/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Controller.AgendaController;
import Model.Cliente;
import Model.Servico;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author USER
 */
public class Agenda extends javax.swing.JFrame {

    private AgendaController controller;

    /**
     * Creates new form Agenda
     */
    public Agenda() {
        initComponents();
        controller = new AgendaController(this);
        iniciar();
    }

    Agenda(int i, Cliente cliente, Servico servico, int i0, String _0915) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Observação = new javax.swing.JLabel();
        Tabela = new javax.swing.JScrollPane();
        TabelaAgendamentos = new javax.swing.JTable();
        BotãoAgendar = new javax.swing.JButton();
        CampoObservação = new javax.swing.JScrollPane();
        TextObservacao = new javax.swing.JTextArea();
        Service = new javax.swing.JLabel();
        Valor = new javax.swing.JLabel();
        Data = new javax.swing.JLabel();
        Hora = new javax.swing.JLabel();
        TextValor = new javax.swing.JTextField();
        TextFormatedData = new javax.swing.JTextField();
        TextFormatedHora = new javax.swing.JTextField();
        TextId = new javax.swing.JTextField();
        JComboboxServico = new javax.swing.JComboBox<>();
        JComboboxCliente = new javax.swing.JComboBox<>();
        Cliente = new javax.swing.JLabel();
        Id = new javax.swing.JLabel();
        Agenda = new javax.swing.JLabel();
        EspaçoPrincipal = new javax.swing.JLabel();
        ImagemPrincipal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Observação.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Observação.setForeground(new java.awt.Color(255, 255, 255));
        Observação.setText("Observação");
        getContentPane().add(Observação, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, -1, -1));

        TabelaAgendamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Cliente", "Serviço", "Valor", "Data", "Hora", "Observação"
            }
        ));
        Tabela.setViewportView(TabelaAgendamentos);

        getContentPane().add(Tabela, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 550, 1090, 360));

        BotãoAgendar.setBackground(new java.awt.Color(0, 204, 51));
        BotãoAgendar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotãoAgendar.setForeground(new java.awt.Color(255, 255, 255));
        BotãoAgendar.setText("Agendar");
        BotãoAgendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotãoAgendarActionPerformed(evt);
            }
        });
        getContentPane().add(BotãoAgendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 470, 610, 40));

        TextObservacao.setColumns(20);
        TextObservacao.setRows(5);
        CampoObservação.setViewportView(TextObservacao);

        getContentPane().add(CampoObservação, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, 610, 230));

        Service.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Service.setForeground(new java.awt.Color(255, 255, 255));
        Service.setText("Service");
        getContentPane().add(Service, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 60, -1));

        Valor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Valor.setForeground(new java.awt.Color(255, 255, 255));
        Valor.setText("Valor $");
        getContentPane().add(Valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 70, -1));

        Data.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Data.setForeground(new java.awt.Color(255, 255, 255));
        Data.setText("Data");
        getContentPane().add(Data, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 70, -1));

        Hora.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Hora.setForeground(new java.awt.Color(255, 255, 255));
        Hora.setText("Hora");
        getContentPane().add(Hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, 60, 30));
        getContentPane().add(TextValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 240, 30));
        getContentPane().add(TextFormatedData, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 240, 30));
        getContentPane().add(TextFormatedHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 480, 240, 30));
        getContentPane().add(TextId, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 240, 30));

        JComboboxServico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  " }));
        JComboboxServico.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                JComboboxServicoItemStateChanged(evt);
            }
        });
        getContentPane().add(JComboboxServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 240, 30));

        getContentPane().add(JComboboxCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 240, 30));

        Cliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Cliente.setForeground(new java.awt.Color(255, 255, 255));
        Cliente.setText("Cliente");
        getContentPane().add(Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 70, -1));

        Id.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Id.setForeground(new java.awt.Color(255, 255, 255));
        Id.setText("Id");
        getContentPane().add(Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 30, -1));

        Agenda.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Agenda.setForeground(new java.awt.Color(255, 255, 255));
        Agenda.setText("Agenda");
        getContentPane().add(Agenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, -1, -1));

        EspaçoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Agenda-PainelFundo.png"))); // NOI18N
        getContentPane().add(EspaçoPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, 1000));

        ImagemPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/AgendaFundo.png"))); // NOI18N
        getContentPane().add(ImagemPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JComboboxServicoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JComboboxServicoItemStateChanged
        this.controller.atualizaValor();
    }//GEN-LAST:event_JComboboxServicoItemStateChanged

    private void BotãoAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotãoAgendarActionPerformed
        this.controller.agendar();
    }//GEN-LAST:event_BotãoAgendarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Agenda;
    private javax.swing.JButton BotãoAgendar;
    private javax.swing.JScrollPane CampoObservação;
    private javax.swing.JLabel Cliente;
    private javax.swing.JLabel Data;
    private javax.swing.JLabel EspaçoPrincipal;
    private javax.swing.JLabel Hora;
    private javax.swing.JLabel Id;
    private javax.swing.JLabel ImagemPrincipal;
    private javax.swing.JComboBox<String> JComboboxCliente;
    private javax.swing.JComboBox<String> JComboboxServico;
    private javax.swing.JLabel Observação;
    private javax.swing.JLabel Service;
    private javax.swing.JScrollPane Tabela;
    private javax.swing.JTable TabelaAgendamentos;
    private javax.swing.JTextField TextFormatedData;
    private javax.swing.JTextField TextFormatedHora;
    private javax.swing.JTextField TextId;
    private javax.swing.JTextArea TextObservacao;
    private javax.swing.JTextField TextValor;
    private javax.swing.JLabel Valor;
    // End of variables declaration//GEN-END:variables

    private void iniciar() {
        this.controller.atualizaTabela();
        this.controller.atualizaCliente();
        this.controller.atualizaServico();
        
       
    }

    public JTable getTabelaAgendamentos() {
        return TabelaAgendamentos;
    }

    public void setTabelaAgendamentos(JTable TabelaAgendamentos) {
        this.TabelaAgendamentos = TabelaAgendamentos;
    }

    public JComboBox<String> getJComboboxCliente() {
        return JComboboxCliente;
    }

    public void setJComboboxCliente(JComboBox<String> JComboboxCliente) {
        this.JComboboxCliente = JComboboxCliente;
    }

    public JComboBox<String> getJComboboxServico() {
        return JComboboxServico;
    }

    public void setJComboboxServico(JComboBox<String> JComboboxServico) {
        this.JComboboxServico = JComboboxServico;
    }

    public JTextField getTextValor() {
        return TextValor;
    }

    public void setTextValor(JTextField TextValor) {
        this.TextValor = TextValor;
    }

    public JTextField getTextFormatedData() {
        return TextFormatedData;
    }

    public void setTextFormatedData(JTextField TextFormatedData) {
        this.TextFormatedData = TextFormatedData;
    }

    public JTextField getTextFormatedHora() {
        return TextFormatedHora;
    }

    public void setTextFormatedHora(JTextField TextFormatedHora) {
        this.TextFormatedHora = TextFormatedHora;
    }

    public JTextField getTextId() {
        return TextId;
    }

    public void setTextId(JTextField TextId) {
        this.TextId = TextId;
    }

    public JTextArea getTextObservacao() {
        return TextObservacao;
    }

    public void setTextObservacao(JTextArea TextObservacao) {
        this.TextObservacao = TextObservacao;
    }
    
    
    
    
    
    
    
    
}
